FutureCode0901/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lib/', include('library.urls')),

    path('magazine/', include('magazine.urls')),
    path('basket/', include('basket.urls')),

]

# Подключаем настройки и статичные ссылки
from django.conf import settings
from django.conf.urls.static import static

# Добавление статичных ссылок на сервер для отображения на сайте картинок
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basket/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', basket_detail, name='basket_detail'),
    path(r'add/<int:product_id>/', basket_add, name='basket_add'),
    path(r'remove/<int:product_id>/', basket_remove, name='basket_rm'),
]

magazine/urls.py
from django.urls import path, include
from .views import *

urlpatterns_template = [
    path('', template_start, name='templates_index_page'),
    path('filter/', template_filter_django, name='templates_filter_example'),
    path('tag/', template_tags_django, name='templates_tag_example'),
]

urlpatterns = [
    path('templates/', include(urlpatterns_template)),
    path('index/',home, name='home_page' ),


    path('catalog/', catalog_product, name='catalog_product_page'),
    path('product/<int:pk>/', product_detail, name='product_detail_page'),
    path('product/create/', product_create, name='create_product_page'),
    path('product/buy/<int:pk>/', buy_product, name='buy_product_page'),

    path('suppliers/', supplier_list, name='catalog_suppliers_page'),
    path('suppliers/create/', supplier_create, name='add'),
    path('suppliers/changeadd/', can_add_change_supplier, name='add_change'),
    path('suppliers/address/', can_change_address, name='change_address'),
    path('suppliers/detail/<int:id>/', supplier_details, name='detail_suppliers_page'),

    path('registration/', user_registration, name='regis'),
    path('login/', user_login, name='log in'),
    path('logout/', user_logout, name='log out'),


    path('anon/', anon, name='anon'),
    path('auth/', auth, name='auth'),


    path('category/', CategoryList.as_view(), name='category_list'),
    path('category/create', CategoryCreate.as_view(), name='category_create'),
    path('category/<int:pk>/detail/', CategoryDetail.as_view(), name='category_detail'),
    path('category/<int:pk>/update/', CategoryUpdate.as_view(), name='category_update'),
    path('category/<int:pk>/delete/', CategoryDelete.as_view(), name='category_delete'),


#     _____________________________pr1__________________________________
    path('order/', OrderList.as_view(), name='order_list'),
    path('order/<int:pk>/', OrderDetail.as_view(), name='order_detail'),
    path('order/create/', OrderCreate.as_view(), name='order_create'),
    path('order/<int:pk>/update/', OrderUpdate.as_view(), name='order_update'),
    path('order/<int:pk>/delete/', OrderDelete.as_view(), name='order_delete'),
    path('order/<int:pk>/sum/', OrderDetails.as_view(), name='order_sum_price'),

    path('api/', test_json, name='api_test'),
    path('api/orders/', order_api_list, name='api_order_list'),
    path('api/orders/<int:pk>/', order_api_detail, name='api_order_detail'),

]

from rest_framework import routers

router = routers.SimpleRouter()
router.register(r'api/products', ProductViewSet, basename='product')
router.register(r'api/supplier', SupplierViewSet, basename='supplier'),
router.register(r'api/supply', SupplyViewSet, basename='supply'),

urlpatterns += router.urls

magazine/models.py
from django.db import models
from django.urls import reverse_lazy

from magazine.utils import sum_price_count

MAX_LENGTH_CHAR = 255

# Create your models here.
class Supplier(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название компании')
    agent_firstname = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Фамилия представителя')
    agent_name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Имя представителя')
    agent_patronymic = models.CharField(max_length=MAX_LENGTH_CHAR, null=True, verbose_name='Отчество представителя')
    agent_telephone = models.CharField(max_length=MAX_LENGTH_CHAR, null=True, verbose_name='Телефон представителя')
    address = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Адрес поставщика')
    is_exists = models.BooleanField(default=True, verbose_name='Логическое удаление')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Поставщик'
        verbose_name_plural = 'Поставщики'

        # Добавление новых пользовательских прав доступа для таблицы
        permissions = [
            ('change_address', 'Возможность изменить адрес доставки'),
            ('can_del_supplier', 'Возможность удалить поставщика'),
        ]
        # После добавление новых разрешений, не забудьте провести миграцию python manage.py makemigrations/migrate
        # Т.к. нужно их добавить в таблицу permissions
        # Но учтите, остальные механизмы проверки и выполнения создаются вручную во view, здесь же просто добавление
        # нового вида доступа, но не механизма



class Supply(models.Model):
    data_supply = models.DateTimeField(verbose_name='Дата поставки')
    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT, verbose_name='Поставщик')

    product = models.ManyToManyField('Product', through='Pos_supply', verbose_name='Продукты')

    def price_supply(self):
        return sum([pos.price_pos_supply() for pos in self.pos_supply_set.all()])
    def __str__(self):
        return f'#{self.pk} - {self.data_supply} {self.supplier.name}'

    class Meta:
        verbose_name = 'Поставка'
        verbose_name_plural = 'Поставки'



class Parametr(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название характеристики')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Характеристика'
        verbose_name_plural = 'Характеристика'

class Category(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')

    def get_absolute_url(self):
        return reverse_lazy('category_detail', kwargs={'pk': self.pk})
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Tag(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name =  'Тег'
        verbose_name_plural = 'Теги'


class Order(models.Model):
    MAGAZINE = "MG"
    COURIER = "CR"
    PICKUPPOINT = "PP"
    TYPE_DELIVERY = [
        (MAGAZINE, "Магазин"),
        (COURIER, "Курьер"),
        (PICKUPPOINT, "Пункт выдачи"),
    ]
    FIO_customer = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='ФИО покупателя')
    comment = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Комментарий')
    delivery_address = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Адрес доставки')
    delivery_type = models.CharField(max_length=2, choices=TYPE_DELIVERY, default=MAGAZINE, verbose_name='Способ доставки')
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')
    date_finish = models.DateTimeField(null=True, blank=True, verbose_name='Дата завершенияя заказа')

    books = models.ManyToManyField('Product', through='Pos_order', verbose_name='Товар')

    def get_absolute_url(self):
        return reverse_lazy('order_sum_price', kwargs={'pk': self.pk})
    def __str__(self):
        return f'{self.pk} {self.FIO_customer} {self.date_create}'

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

class Product(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название товара')
    description = models.TextField(null=True, blank=True, verbose_name='Описание товара')
    price = models.FloatField(verbose_name='Цена')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления записи')
    photo = models.ImageField(upload_to='image/%Y/%m/%d', null=True,blank=True, verbose_name='Фотография товара')
    exists = models.BooleanField(default=True, verbose_name='В наличии?')

    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='Категория')
    tag = models.ManyToManyField(Tag, blank=True, verbose_name='Тег')
    parametr = models.ManyToManyField(Parametr, through='Pos_parametr', verbose_name='Характеристики')

    def get_absolute_url(self):
        return reverse_lazy('product_detail_page', kwargs={'pk': self.pk})
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Pos_parametr(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Продукт')
    parametr = models.ForeignKey(Parametr, on_delete=models.PROTECT, verbose_name='Характеристика')

    value = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Значение')

    def __str__(self):
        return f'{self.product.name} - {self.value}'

    class Meta:
        verbose_name = 'Позиция характеристики'
        verbose_name_plural = 'Позиции характеристик'


class Pos_supply(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Продукт')
    supply = models.ForeignKey(Supply,on_delete=models.PROTECT, verbose_name='Поставка' )

    count = models.PositiveIntegerField(verbose_name='Количество продукта')

    def price_pos_supply(self):
        return sum_price_count(price=self.product.price, count=self.count)
    def __str__(self):
        return f'{self.product.name} - #{self.supply.pk}'

    class Meta:
        verbose_name = 'Позиция поставки'
        verbose_name_plural = 'Позиции поставок'

class Pos_order(models.Model):
    product = models.ForeignKey('Product', on_delete=models.PROTECT, verbose_name='Продукт')
    order = models.ForeignKey('Order', on_delete=models.PROTECT, verbose_name='Заказ')
    count = models.PositiveIntegerField(default=1, verbose_name='Количество продукта')
    discount = models.PositiveIntegerField(default=0, verbose_name='Скидка продукта')

    def sum_pos_order(self):
        return sum_price_count(price=self.product.price, count=self.count, discount=self.discount)

    def __str__(self):
        return f"{self.pk} {self.product.name} {self.order.FIO_customer}"

    class Meta:
        verbose_name = 'Позиция заказа'
        verbose_name_plural = 'Позиции заказов'

magazine/forms.py
import re
from django.core.exceptions import ValidationError
from django import forms
from .models import *

class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = (
            'name',
            'agent_firstname',
            'agent_name',
            'agent_patronymic',
            'agent_telephone',
            'address',
        )

        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'agent_firstname': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'agent_name': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'agent_patronymic': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'agent_telephone': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'address': forms.TextInput(
                attrs={'class': 'form-control'}
            ),

        }
    def clean_agent_telephone(self):
        agent_telephone = self.cleaned_data['agent_telephone']
        if re.match(r'\+7\(\d{3}\)\d{3}-\d{2}-\d{2}', agent_telephone):
            return agent_telephone
        raise ValidationError('Телефон не соответствует шаблону')


class SupplyForm(forms.ModelForm):
    class Meta:
        model = Supply
        fields = (
            'data_supply',
            'supplier',
        )

class Pos_supplyForm(forms.ModelForm):
    class Meta:
        model = Pos_supply
        fields = (
            'product',
            'supply',
            'count',
        )
class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = (
            'name',
            'description',
        )
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = (
            'name',
            'description',
        )
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = (
            'FIO_customer',
            'delivery_address',
            'delivery_type',
            'date_finish'
        )

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            'name',
            'description',
            'price',
            'photo',
            'exists',
            'category',
            'tag',
        )

        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'description': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'price': forms.NumberInput(
                attrs={'class': 'form-control'}
            ),
            'photo': forms.FileInput(
                attrs={'class': 'form-control'}
            ),

        }


class ProductFilterForm(forms.Form):
    name = forms.CharField(
        max_length=150,
        min_length=2,
        strip=True,
        label='Название товара',
        required=False,
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )

    )

    max_price = forms.DecimalField(
        label='Максимальная цена товара',
        required=False,
        min_value=0,
        max_digits=10,
        decimal_places=2,
        step_size=0.01,
        widget=forms.NumberInput(
            attrs={'class': 'form-control'}
        )
    )

    min_price = forms.DecimalField(
        label='Минимальная цена товара',
        required=False,
        min_value=0,
        max_digits=10,
        decimal_places=2,
        step_size=0.01,
        widget=forms.NumberInput(
            attrs={'class': 'form-control'}
        )
    )


# ------------------------- auth ---------------------------

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    username = forms.CharField(
        label='Логин пользователя',
        widget=forms.TextInput(attrs={'class': 'form-control', }),
        min_length=2
    )
    email = forms.CharField(
        label='Электронная почта',
        widget=forms.EmailInput(attrs={'class': 'form-control', }),
    )
    password1 = forms.CharField(
        label='Придумайте пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control', }),
    )
    password2 = forms.CharField(
        label='Повторите пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control', }),
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Логин пользователя',
        widget=forms.TextInput(attrs={'class': 'form-control', }),
        min_length=2
    )
    password = forms.CharField(
        label='Ваш пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control', }),
    )

magazine/templates/magazine/email.html
{% extends 'base.html' %}


{% block title_name %}
    Отправка письма
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_div }}
        <button type="submit" class="btn btn-primary">Отправить данные </button>
    </form>
    <a href="{% url 'home_page' %}" class="btn btn-info">Обратно на домашнюю страницу</a>

{% endblock %}

magazine/templates/magazine/index.html
{# Сначала нам нужно выбрать и импортировать скелет (в нашем случае base.html) #}
{# После чего в PyCharm появится подсказки в выбора имени блоков#}
{% extends 'base.html' %}

{# Вызывая блок мы его переопределяем, а именно то, что находится внутри него #}
{# Соответственно, в названии нашей вкладки будет "Домашняя страница", а не "НАЗВАНИЕ СТРАНИЦЫ" #}
{% block title_name %}
    Домашняя страница
{% endblock %}

{# Также можно вызвать блок с контентом по умолчанию и переопределяя его тем самым очистить #}
{# К примеру, стили bootstrap подключаются через скелет внутри блока link_boostrap #}
{# и если вызвать данный блок указав пустоту, то стили пропадут, #}
{# т.к. изначально прописанные значения изменять на пустоту #}

{#{% block link_boostrap %}#}
{#	#}
{#{% endblock %}#}

{% block content %}
    <ul>
        <li><a href="{% url 'catalog_product_page' %}">Каталог продуктов</a></li>
        <li><a href="{% url 'catalog_suppliers_page' %}">Каталог поставщиков</a></li>
        {% if request.user.is_anonymous %}
            <li><a href="{% url 'log in' %}">Авторизация</a></li>
            <li><a href="{% url 'regis' %}">Регистрация</a></li>
        {% else %}
            <li><a href="{% url 'log out' %}">Выход из аккаунта</a></li>
        {% endif %}

        <li><a href="{% url 'anon' %}">Аноним</a></li>
        <li><a href="{% url 'auth' %}">Авторизованный</a></li>
        <li><a href="{% url 'add' %}">Добавление продукта</a></li>
        <li><a href="{% url 'add_change' %}">Добавление и изменение продукта</a></li>
        <li><a href="{% url 'change_address' %}">Изменение адреса доставки</a></li>

    </ul>
    <div>
        {% if request.user.is_anonymous %}
            <h2>Аноним</h2>
        {% endif %}
        {% if request.user.is_authenticated %}
            <h2>Авторизованный</h2>
        {% endif %}

        {# проверка прав доступа на фронтэнде происходит через perms#}
        {% if perms.magazine.add_product %}
            <h2>Можешь добавить продукт</h2>
        {% endif %}
        {% if perms.magazine.add_product and perms.magazine.change_product %}
            <h2>Можешь добавить и изменить продукт</h2>
        {% endif %}
        {% if perms.magazine.change_delivery_type %}
            <h2>Можешь изменить тип доставки</h2>
        {% endif %}

    </div>
{% endblock %}



{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Домашняя страница</title>#}
{#</head>#}
{#<body>#}
{#{% if messages %}#}
{#    <h1>ОПОВЕЩЕНИЕ</h1>#}
{#    <ul class="messages">#}
{#        {% for message in messages %}#}
{#            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>#}
{#        {% endfor %}#}
{#    </ul>#}
{#{% endif %}#}
{#    <h1>Домашняя страница</h1>#}
{#    <ul>#}
{#        <li><a href="{% url 'catalog_product_page' %}">Каталог продуктов</a></li>#}
{#        <li>#}
{##}
{#            <a href="{% url 'catalog_suppliers_page' %}">Список поставщиков </a>#}
{#        </li>#}
         {# Проверка на уровне фронтенда #}
    {#    Проверка человека на авторизованность (схожая штука есть в views.py) #}
    {# Если человек анонимный, то выводим авторизацию и регистрацию #}
    {# Если человек авторизовался, то выводим выход из аккаунта #}
{#    {% if request.user.is_anonymous %}#}
{#        <li><a href="{% url 'log in' %}">Авторизация</a></li>#}
{#        <li><a href="{% url 'regis' %}">Регистрация</a></li>#}
{#    {% else %}#}
{#        <li><a href="{% url 'log out' %}">Выход из аккаунта</a></li>#}
{#    {% endif %}#}
{##}
{#    <li><a href="{% url 'anon' %}">Аноним</a></li>#}
{#    <li><a href="{% url 'auth' %}">Авторизованный</a></li>#}
{#    <li><a href="{% url 'add' %}">Добавление поставщика</a></li>#}
{#    <li><a href="{% url 'add_change' %}">Добавление и изменение поставщика</a></li>#}
{#    <li><a href="{% url 'change_address' %}">Изменение адреса</a></li>#}
{##}
{#    </ul>#}
{#<div>#}
{#    {% if request.user.is_anonymous %}#}
{#        <h2>Аноним</h2>#}
{#    {% endif %}#}
{#    {% if request.user.is_authenticated %}#}
{#        <h2>Авторизованный</h2>#}
{#    {% endif %}#}
{##}
{# проверка прав доступа на фронтэнде происходит через perms#}
{#    {% if perms.magazine.add_supplier %}#}
{#        <h2>Можешь добавить поставщика</h2>#}
{#    {% endif %}#}
{#    {% if perms.magazine.add_supplier and perms.magazine.change_supplier %}#}
{#        <h2>Можешь добавить и изменить поставщика</h2>#}
{#    {% endif %}#}
{#    {% if perms.magazine.change_address %}#}
{#        <h2>Можешь изменить адресс</h2>#}
{#    {% endif %}#}
{##}
{#</div>#}
{#</body>#}
{#</html>#}