FutureCode0901/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lib/', include('library.urls')),

    path('magazine/', include('magazine.urls')),
    path('basket/', include('basket.urls')),

]

# Подключаем настройки и статичные ссылки
from django.conf import settings
from django.conf.urls.static import static

# Добавление статичных ссылок на сервер для отображения на сайте картинок
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basket/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', basket_detail, name='basket_detail'),
    path(r'add/<int:product_id>/', basket_add, name='basket_add'),
    path(r'remove/<int:product_id>/', basket_remove, name='basket_rm'),
]

magazine/urls.py
from django.urls import path, include
from .views import *

urlpatterns_template = [
    path('', template_start, name='templates_index_page'),
    path('filter/', template_filter_django, name='templates_filter_example'),
    path('tag/', template_tags_django, name='templates_tag_example'),
]

urlpatterns = [
    path('templates/', include(urlpatterns_template)),
    path('index/',home, name='home_page' ),


    path('catalog/', catalog_product, name='catalog_product_page'),
    path('product/<int:pk>/', product_detail, name='product_detail_page'),
    path('product/create/', product_create, name='create_product_page'),
    path('product/buy/<int:pk>/', buy_product, name='buy_product_page'),

    path('suppliers/', supplier_list, name='catalog_suppliers_page'),
    path('suppliers/create/', supplier_create, name='add'),
    path('suppliers/changeadd/', can_add_change_supplier, name='add_change'),
    path('suppliers/address/', can_change_address, name='change_address'),
    path('suppliers/detail/<int:id>/', supplier_details, name='detail_suppliers_page'),

    path('registration/', user_registration, name='regis'),
    path('login/', user_login, name='log in'),
    path('logout/', user_logout, name='log out'),


    path('anon/', anon, name='anon'),
    path('auth/', auth, name='auth'),


    path('category/', CategoryList.as_view(), name='category_list'),
    path('category/create', CategoryCreate.as_view(), name='category_create'),
    path('category/<int:pk>/detail/', CategoryDetail.as_view(), name='category_detail'),
    path('category/<int:pk>/update/', CategoryUpdate.as_view(), name='category_update'),
    path('category/<int:pk>/delete/', CategoryDelete.as_view(), name='category_delete'),


#     _____________________________pr1__________________________________
    path('order/', OrderList.as_view(), name='order_list'),
    path('order/<int:pk>/', OrderDetail.as_view(), name='order_detail'),
    path('order/create/', OrderCreate.as_view(), name='order_create'),
    path('order/<int:pk>/update/', OrderUpdate.as_view(), name='order_update'),
    path('order/<int:pk>/delete/', OrderDelete.as_view(), name='order_delete'),
    path('order/<int:pk>/sum/', OrderDetails.as_view(), name='order_sum_price'),

    path('api/', test_json, name='api_test'),
    path('api/orders/', order_api_list, name='api_order_list'),
    path('api/orders/<int:pk>/', order_api_detail, name='api_order_detail'),

]

from rest_framework import routers

router = routers.SimpleRouter()
router.register(r'api/products', ProductViewSet, basename='product')
router.register(r'api/supplier', SupplierViewSet, basename='supplier'),
router.register(r'api/supply', SupplyViewSet, basename='supply'),

urlpatterns += router.urls

magazine/models.py
from django.db import models
from django.urls import reverse_lazy

from magazine.utils import sum_price_count

MAX_LENGTH_CHAR = 255

# Create your models here.
class Supplier(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название компании')
    agent_firstname = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Фамилия представителя')
    agent_name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Имя представителя')
    agent_patronymic = models.CharField(max_length=MAX_LENGTH_CHAR, null=True, verbose_name='Отчество представителя')
    agent_telephone = models.CharField(max_length=MAX_LENGTH_CHAR, null=True, verbose_name='Телефон представителя')
    address = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Адрес поставщика')
    is_exists = models.BooleanField(default=True, verbose_name='Логическое удаление')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Поставщик'
        verbose_name_plural = 'Поставщики'

        # Добавление новых пользовательских прав доступа для таблицы
        permissions = [
            ('change_address', 'Возможность изменить адрес доставки'),
            ('can_del_supplier', 'Возможность удалить поставщика'),
        ]
        # После добавление новых разрешений, не забудьте провести миграцию python manage.py makemigrations/migrate
        # Т.к. нужно их добавить в таблицу permissions
        # Но учтите, остальные механизмы проверки и выполнения создаются вручную во view, здесь же просто добавление
        # нового вида доступа, но не механизма



class Supply(models.Model):
    data_supply = models.DateTimeField(verbose_name='Дата поставки')
    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT, verbose_name='Поставщик')

    product = models.ManyToManyField('Product', through='Pos_supply', verbose_name='Продукты')

    def price_supply(self):
        return sum([pos.price_pos_supply() for pos in self.pos_supply_set.all()])
    def __str__(self):
        return f'#{self.pk} - {self.data_supply} {self.supplier.name}'

    class Meta:
        verbose_name = 'Поставка'
        verbose_name_plural = 'Поставки'



class Parametr(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название характеристики')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Характеристика'
        verbose_name_plural = 'Характеристика'

class Category(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')

    def get_absolute_url(self):
        return reverse_lazy('category_detail', kwargs={'pk': self.pk})
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Tag(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name =  'Тег'
        verbose_name_plural = 'Теги'


class Order(models.Model):
    MAGAZINE = "MG"
    COURIER = "CR"
    PICKUPPOINT = "PP"
    TYPE_DELIVERY = [
        (MAGAZINE, "Магазин"),
        (COURIER, "Курьер"),
        (PICKUPPOINT, "Пункт выдачи"),
    ]
    FIO_customer = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='ФИО покупателя')
    comment = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Комментарий')
    delivery_address = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Адрес доставки')
    delivery_type = models.CharField(max_length=2, choices=TYPE_DELIVERY, default=MAGAZINE, verbose_name='Способ доставки')
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')
    date_finish = models.DateTimeField(null=True, blank=True, verbose_name='Дата завершенияя заказа')

    books = models.ManyToManyField('Product', through='Pos_order', verbose_name='Товар')

    def get_absolute_url(self):
        return reverse_lazy('order_sum_price', kwargs={'pk': self.pk})
    def __str__(self):
        return f'{self.pk} {self.FIO_customer} {self.date_create}'

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

class Product(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название товара')
    description = models.TextField(null=True, blank=True, verbose_name='Описание товара')
    price = models.FloatField(verbose_name='Цена')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления записи')
    photo = models.ImageField(upload_to='image/%Y/%m/%d', null=True,blank=True, verbose_name='Фотография товара')
    exists = models.BooleanField(default=True, verbose_name='В наличии?')

    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='Категория')
    tag = models.ManyToManyField(Tag, blank=True, verbose_name='Тег')
    parametr = models.ManyToManyField(Parametr, through='Pos_parametr', verbose_name='Характеристики')

    def get_absolute_url(self):
        return reverse_lazy('product_detail_page', kwargs={'pk': self.pk})
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Pos_parametr(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Продукт')
    parametr = models.ForeignKey(Parametr, on_delete=models.PROTECT, verbose_name='Характеристика')

    value = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Значение')

    def __str__(self):
        return f'{self.product.name} - {self.value}'

    class Meta:
        verbose_name = 'Позиция характеристики'
        verbose_name_plural = 'Позиции характеристик'


class Pos_supply(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Продукт')
    supply = models.ForeignKey(Supply,on_delete=models.PROTECT, verbose_name='Поставка' )

    count = models.PositiveIntegerField(verbose_name='Количество продукта')

    def price_pos_supply(self):
        return sum_price_count(price=self.product.price, count=self.count)
    def __str__(self):
        return f'{self.product.name} - #{self.supply.pk}'

    class Meta:
        verbose_name = 'Позиция поставки'
        verbose_name_plural = 'Позиции поставок'

class Pos_order(models.Model):
    product = models.ForeignKey('Product', on_delete=models.PROTECT, verbose_name='Продукт')
    order = models.ForeignKey('Order', on_delete=models.PROTECT, verbose_name='Заказ')
    count = models.PositiveIntegerField(default=1, verbose_name='Количество продукта')
    discount = models.PositiveIntegerField(default=0, verbose_name='Скидка продукта')

    def sum_pos_order(self):
        return sum_price_count(price=self.product.price, count=self.count, discount=self.discount)

    def __str__(self):
        return f"{self.pk} {self.product.name} {self.order.FIO_customer}"

    class Meta:
        verbose_name = 'Позиция заказа'
        verbose_name_plural = 'Позиции заказов'

magazine/forms.py
import re
from django.core.exceptions import ValidationError
from django import forms
from .models import *

class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = (
            'name',
            'agent_firstname',
            'agent_name',
            'agent_patronymic',
            'agent_telephone',
            'address',
        )

        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'agent_firstname': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'agent_name': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'agent_patronymic': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'agent_telephone': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'address': forms.TextInput(
                attrs={'class': 'form-control'}
            ),

        }
    def clean_agent_telephone(self):
        agent_telephone = self.cleaned_data['agent_telephone']
        if re.match(r'\+7\(\d{3}\)\d{3}-\d{2}-\d{2}', agent_telephone):
            return agent_telephone
        raise ValidationError('Телефон не соответствует шаблону')


class SupplyForm(forms.ModelForm):
    class Meta:
        model = Supply
        fields = (
            'data_supply',
            'supplier',
        )

class Pos_supplyForm(forms.ModelForm):
    class Meta:
        model = Pos_supply
        fields = (
            'product',
            'supply',
            'count',
        )
class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = (
            'name',
            'description',
        )
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = (
            'name',
            'description',
        )
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = (
            'FIO_customer',
            'delivery_address',
            'delivery_type',
            'date_finish'
        )

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            'name',
            'description',
            'price',
            'photo',
            'exists',
            'category',
            'tag',
        )

        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'description': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'price': forms.NumberInput(
                attrs={'class': 'form-control'}
            ),
            'photo': forms.FileInput(
                attrs={'class': 'form-control'}
            ),

        }


class ProductFilterForm(forms.Form):
    name = forms.CharField(
        max_length=150,
        min_length=2,
        strip=True,
        label='Название товара',
        required=False,
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )

    )

    max_price = forms.DecimalField(
        label='Максимальная цена товара',
        required=False,
        min_value=0,
        max_digits=10,
        decimal_places=2,
        step_size=0.01,
        widget=forms.NumberInput(
            attrs={'class': 'form-control'}
        )
    )

    min_price = forms.DecimalField(
        label='Минимальная цена товара',
        required=False,
        min_value=0,
        max_digits=10,
        decimal_places=2,
        step_size=0.01,
        widget=forms.NumberInput(
            attrs={'class': 'form-control'}
        )
    )


# ------------------------- auth ---------------------------

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    username = forms.CharField(
        label='Логин пользователя',
        widget=forms.TextInput(attrs={'class': 'form-control', }),
        min_length=2
    )
    email = forms.CharField(
        label='Электронная почта',
        widget=forms.EmailInput(attrs={'class': 'form-control', }),
    )
    password1 = forms.CharField(
        label='Придумайте пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control', }),
    )
    password2 = forms.CharField(
        label='Повторите пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control', }),
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Логин пользователя',
        widget=forms.TextInput(attrs={'class': 'form-control', }),
        min_length=2
    )
    password = forms.CharField(
        label='Ваш пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control', }),
    )

magazine/templates/magazine/product/catalog.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <form>
        {{ form.as_div }}

        <button type="submit" class="btn btn-info">Применить фильтр</button>
    </form>

    {% if perms.magazine.add_product or perms.magazine.add_supplier %}
        <div class="container">
            {% if perms.magazine.add_product %}
                <a href="{% url 'create_product_page' %}" class="btn btn-success">Создать товар</a>
            {% endif %}

            {% if perms.magazine.add_supplier %}
                <a href="{% url 'add' %}" class="btn btn-success">Создать поставщика</a>
            {% endif %}
        </div>
    {% endif %}
    <div class="container">
        <div class="row">
            {% for object in list_object %}
                <div class="col-4">
                    <div class="card" style="width: 18rem;">
                        {% if object.photo %}
                            <img src="{{ object.photo.url }}" class="card-img-top" alt="...">
                        {% else %}
                            <img src="{% static 'magazine/image/98094191.jpg' %}" class="card-img-top" alt="...">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ object.name }}</h5>
                            <h6 class="card-subtitle mb-2 text-body-secondary">
                                Категория: {{ object.category.name }}</h6>
                            <h6 class="card-subtitle mb-2 text-body-secondary">
                                Теги: {% for tag in object.tag.all %} {{ tag.name }}. {% endfor %}
                            </h6>
                            <p class="card-text">{{ object.description }}</p>
                            <p class="card-text">Цена: {{ object.price }}</p>
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'product_detail_page' object.pk %}"
                                   class="btn btn-primary">Подробнее</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    </div>
{% endblock %}

{#{% load static %}#}
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Каталог книг (по фильтрации)</title>#}
{#    <link rel="stylesheet" href="{% static 'magazine/css/bootstrap.css' %}">#}
{##}
{#    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">#}
{#        <symbol id="info-fill" viewBox="0 0 16 16">#}
{#            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>#}
{#        </symbol>#}
{#        <symbol id="success-fill" viewBox="0 0 16 16">#}
{#            <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>#}
{#        </symbol>#}
{#        <symbol id="warning-fill" viewBox="0 0 16 16">#}
{#            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>#}
{#        </symbol>#}
{#        <symbol id="danger-fill" viewBox="0 0 16 16">#}
{#            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>#}
{#        </symbol>#}
{#    </svg>#}
{##}
{#</head>#}
{#<body>#}
{#<div class="container">#}
{#    <div class="container">#}
{#        <div class="row">#}
{#            <div class="col-8">#}
{#                <ul>#}
{#                    {% if request.user.is_anonymous %}#}
{#                        <li><a class="btn btn-primary" href="{% url 'log in' %}">Авторизация</a></li>#}
{#                        <li><a class="btn btn-primary" href="{% url 'regis' %}">Регистрация</a></li>#}
{#                    {% else %}#}
{#                        <li><a class="btn btn-primary" href="{% url 'log out' %}">Выход из аккаунта</a></li>#}
{#                    {% endif %}#}
{#                </ul>#}
{#            </div>#}
{#            <div class="col-4">#}
{#                Здравствуйте, {{ user }}#}
{#            </div>#}
{#        </div>#}
{##}
{#    </div>#}
{##}
{##}
{#    <h1>Каталог книг</h1>#}
{##}
{#    {% if messages %}#}
{#        <div class="container">#}
{#            <div class="row">#}
{##}
{#                {% for message in messages %}#}
{#                    {% if message.tags == 'error' %}#}
{##}
{#                        <div class="alert alert-danger d-flex align-items-center" role="alert">#}
{#                            <svg class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2 " role="img"#}
{#                                 aria-label="danger:">#}
{#                                <use xlink:href="#danger-fill"/>#}
{#                            </svg>#}
{#                            <div>#}
{#                                {{ message }}#}
{#                            </div>#}
{#                        </div>#}
{#                    {% else %}#}
{#                        <div class="alert alert-{{ message.tags }} d-flex align-items-center" role="alert">#}
{#                            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="{{ message.tags }}:">#}
{#                                <use xlink:href="#{{ message.tags }}-fill"/>#}
{#                            </svg>#}
{#                            <div>#}
{#                                {{ message }}#}
{#                            </div>#}
{#                        </div>#}
{#                    {% endif %}#}
{#                {% endfor %}#}
{#            </div>#}
{#        </div>#}
{#    {% endif %}#}
{##}
{##}
{##}
{##}
{##}
{##}
{#    <form>#}
{#        {{ form.as_div }}#}
{##}
{#        <button type="submit" class="btn btn-info">Применить фильтр</button>#}
{#    </form>#}
{##}
{#    {% if perms.magazine.add_product or perms.magazine.add_supplier %}#}
{#        <div class="container">#}
{#            {% if perms.magazine.add_product %}#}
{#                <a href="{% url 'create_product_page' %}" class="btn btn-success">Создать товар</a>#}
{#            {% endif %}#}
{##}
{#            {% if perms.magazine.add_supplier %}#}
{#                <a href="{% url 'add' %}" class="btn btn-success">Создать поставщика</a>#}
{#            {% endif %}#}
{#        </div>#}
{#    {% endif %}#}
{#    <div class="container">#}
{#        <div class="row">#}
{#            {% for object in list_object %}#}
{#                <div class="col-4">#}
{#                    <div class="card" style="width: 18rem;">#}
{#                        {% if object.photo %}#}
{#                            <img src="{{ object.photo.url }}" class="card-img-top" alt="...">#}
{#                        {% else %}#}
{#                            <img src="{% static 'magazine/image/98094191.jpg' %}" class="card-img-top" alt="...">#}
{#                        {% endif %}#}
{#                        <div class="card-body">#}
{#                            <h5 class="card-title">{{ object.name }}</h5>#}
{#                            <h6 class="card-subtitle mb-2 text-body-secondary">#}
{#                                Категория: {{ object.category.name }}</h6>#}
{#                            <h6 class="card-subtitle mb-2 text-body-secondary">#}
{#                                Теги: {% for tag in object.tag.all %} {{ tag.name }}. {% endfor %}#}
{#                            </h6>#}
{#                            <p class="card-text">{{ object.description }}</p>#}
{#                            <p class="card-text">Цена: {{ object.price }}</p>#}
{#                            {% if request.user.is_authenticated %}#}
{#                                <a href="{% url 'product_detail_page' object.pk %}"#}
{#                                   class="btn btn-primary">Подробнее</a>#}
{#                            {% endif %}#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            {% endfor %}#}
{#        </div>#}
{#    </div>#}
{#</div>#}
{#</body>#}
{#</html>#}

magazine/templates/magazine/product/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Создание товар</title>
    <link rel="stylesheet" href="{% static 'magazine/css/bootstrap.css' %}">
</head>
<body>
<div class="container">
<h1>Создание товар</h1>

    <form method="post" enctype="multipart/form-data">
{#        Не забываем добавлять csrf_token, он нужен для передачи данных через POST #}
        {% csrf_token %}
        {{ form.as_div }}
        <button type="submit" class="btn btn-primary">Создать товар</button>
    </form>
    <a href="{% url 'catalog_product_page' %}" class="btn btn-info">Обратно к каталогу</a>
</div>
</body>
</html>

magazine/templates/magazine/product/detail.html
{% load default_style %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ product }}</title>
    <link rel="stylesheet" href="{% static 'magazine/css/bootstrap.css' %}">
</head>
<body>
<div class="container ">
    <div class="col-2"></div>
    <div class="row">
        <a href="{% url 'catalog_product_page' %}"> < Обратно к каталогу</a>
    </div>

    <div class="row">
        <div class="col-4">
            <div class="container">
                <h1>Продукт: {{ product.name }}</h1>
                <p>Описание: {{ product.description }}</p>
                <h3>Цена: {{ product.price }}</h3>
            </div>
        </div>
        <div class="col-6">
            {% if product.photo %}
                <img src="{{ product.photo.url }}" class="img-thumbnail rounded" alt="...">
            {% else %}
                <img src="{% static 'magazine/image/98094191.jpg' %}" class="img-thumbnail rounded" alt="...">
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="container">
            <h2>Категория</h2>
            <a href="#">{{ product.category.name }}
                {% if product.category.description %}
                    Описание категории: {{ product.category.description }}
                {% endif %}
            </a>
        </div>
    </div>

    <div class="row">
        <div class="container">
            <h2>Тэги</h2>

            {# Классическое использование вывода информации #}
            <div>
                {% for tag in product.tag.all %}
                    <a href="#">{{ tag }}.</a>
                {% endfor %}
            </div>
            <br>
            {# Использование тега в качестве вывода информации #}
            <div>
                {% show_tags product %}
            </div>
            <br>
            {# Использование тега включения в качестве вывода информации #}
            <div>
                {% show_tags_inclusion product %}
            </div>
        </div>
    </div>

    <div class="row">
        <h2>Характеристики</h2>

        {% for pos_parametr in product.pos_parametr_set.all %}
            <div class="col-4">{{ pos_parametr.parametr }} : {{ pos_parametr.value }}</div>
        {% endfor %}

    </div>

    {% if request.user.is_authenticated %}
            <form method="post" action="{% url 'basket_add' product.pk %}">
        {% csrf_token %}
        {{ form_basket }}
        <button type="submit" class="btn btn-success">Добавить в корзину</button>
            </form>
    {% endif %}

    {% if perms.magazine.add_product %}

        <div class="row">
            <h2>Заказы:</h2>

            {% for order in product.order_set.all %}
                <ul>
                    <li>{{ order }}</li>
                </ul>
            {% endfor %}
        </div>


        <div class="row">
            <h2>Поставки:</h2>

            {% for supply in product.supply_set.all %}
                <ul>
                    <li>{{ supply }}</li>
                </ul>
            {% endfor %}
        </div>
    {% endif %}
</div>
</body>
</html>