FutureCode0901/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lib/', include('library.urls')),

    path('magazine/', include('magazine.urls')),
    path('basket/', include('basket.urls')),

]

# Подключаем настройки и статичные ссылки
from django.conf import settings
from django.conf.urls.static import static

# Добавление статичных ссылок на сервер для отображения на сайте картинок
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basket/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', basket_detail, name='basket_detail'),
    path(r'add/<int:product_id>/', basket_add, name='basket_add'),
    path(r'remove/<int:product_id>/', basket_remove, name='basket_rm'),
]

magazine/urls.py
from django.urls import path, include
from .views import *

urlpatterns_template = [
    path('', template_start, name='templates_index_page'),
    path('filter/', template_filter_django, name='templates_filter_example'),
    path('tag/', template_tags_django, name='templates_tag_example'),
]

urlpatterns = [
    path('templates/', include(urlpatterns_template)),
    path('index/',home, name='home_page' ),


    path('catalog/', catalog_product, name='catalog_product_page'),
    path('product/<int:pk>/', product_detail, name='product_detail_page'),
    path('product/create/', product_create, name='create_product_page'),
    path('product/buy/<int:pk>/', buy_product, name='buy_product_page'),

    path('suppliers/', supplier_list, name='catalog_suppliers_page'),
    path('suppliers/create/', supplier_create, name='add'),
    path('suppliers/changeadd/', can_add_change_supplier, name='add_change'),
    path('suppliers/address/', can_change_address, name='change_address'),
    path('suppliers/detail/<int:id>/', supplier_details, name='detail_suppliers_page'),

    path('registration/', user_registration, name='regis'),
    path('login/', user_login, name='log in'),
    path('logout/', user_logout, name='log out'),


    path('anon/', anon, name='anon'),
    path('auth/', auth, name='auth'),


    path('category/', CategoryList.as_view(), name='category_list'),
    path('category/create', CategoryCreate.as_view(), name='category_create'),
    path('category/<int:pk>/detail/', CategoryDetail.as_view(), name='category_detail'),
    path('category/<int:pk>/update/', CategoryUpdate.as_view(), name='category_update'),
    path('category/<int:pk>/delete/', CategoryDelete.as_view(), name='category_delete'),


#     _____________________________pr1__________________________________
    path('order/', OrderList.as_view(), name='order_list'),
    path('order/<int:pk>/', OrderDetail.as_view(), name='order_detail'),
    path('order/create/', OrderCreate.as_view(), name='order_create'),
    path('order/<int:pk>/update/', OrderUpdate.as_view(), name='order_update'),
    path('order/<int:pk>/delete/', OrderDelete.as_view(), name='order_delete'),
    path('order/<int:pk>/sum/', OrderDetails.as_view(), name='order_sum_price'),

    path('api/', test_json, name='api_test'),
    path('api/orders/', order_api_list, name='api_order_list'),
    path('api/orders/<int:pk>/', order_api_detail, name='api_order_detail'),

]

from rest_framework import routers

router = routers.SimpleRouter()
router.register(r'api/products', ProductViewSet, basename='product')
router.register(r'api/supplier', SupplierViewSet, basename='supplier'),
router.register(r'api/supply', SupplyViewSet, basename='supply'),

urlpatterns += router.urls

magazine/models.py
from django.db import models
from django.urls import reverse_lazy

from magazine.utils import sum_price_count

MAX_LENGTH_CHAR = 255

# Create your models here.
class Supplier(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название компании')
    agent_firstname = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Фамилия представителя')
    agent_name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Имя представителя')
    agent_patronymic = models.CharField(max_length=MAX_LENGTH_CHAR, null=True, verbose_name='Отчество представителя')
    agent_telephone = models.CharField(max_length=MAX_LENGTH_CHAR, null=True, verbose_name='Телефон представителя')
    address = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Адрес поставщика')
    is_exists = models.BooleanField(default=True, verbose_name='Логическое удаление')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Поставщик'
        verbose_name_plural = 'Поставщики'

        # Добавление новых пользовательских прав доступа для таблицы
        permissions = [
            ('change_address', 'Возможность изменить адрес доставки'),
            ('can_del_supplier', 'Возможность удалить поставщика'),
        ]
        # После добавление новых разрешений, не забудьте провести миграцию python manage.py makemigrations/migrate
        # Т.к. нужно их добавить в таблицу permissions
        # Но учтите, остальные механизмы проверки и выполнения создаются вручную во view, здесь же просто добавление
        # нового вида доступа, но не механизма



class Supply(models.Model):
    data_supply = models.DateTimeField(verbose_name='Дата поставки')
    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT, verbose_name='Поставщик')

    product = models.ManyToManyField('Product', through='Pos_supply', verbose_name='Продукты')

    def price_supply(self):
        return sum([pos.price_pos_supply() for pos in self.pos_supply_set.all()])
    def __str__(self):
        return f'#{self.pk} - {self.data_supply} {self.supplier.name}'

    class Meta:
        verbose_name = 'Поставка'
        verbose_name_plural = 'Поставки'



class Parametr(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название характеристики')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Характеристика'
        verbose_name_plural = 'Характеристика'

class Category(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')

    def get_absolute_url(self):
        return reverse_lazy('category_detail', kwargs={'pk': self.pk})
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Tag(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name =  'Тег'
        verbose_name_plural = 'Теги'


class Order(models.Model):
    MAGAZINE = "MG"
    COURIER = "CR"
    PICKUPPOINT = "PP"
    TYPE_DELIVERY = [
        (MAGAZINE, "Магазин"),
        (COURIER, "Курьер"),
        (PICKUPPOINT, "Пункт выдачи"),
    ]
    FIO_customer = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='ФИО покупателя')
    comment = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Комментарий')
    delivery_address = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Адрес доставки')
    delivery_type = models.CharField(max_length=2, choices=TYPE_DELIVERY, default=MAGAZINE, verbose_name='Способ доставки')
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')
    date_finish = models.DateTimeField(null=True, blank=True, verbose_name='Дата завершенияя заказа')

    books = models.ManyToManyField('Product', through='Pos_order', verbose_name='Товар')

    def get_absolute_url(self):
        return reverse_lazy('order_sum_price', kwargs={'pk': self.pk})
    def __str__(self):
        return f'{self.pk} {self.FIO_customer} {self.date_create}'

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

class Product(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название товара')
    description = models.TextField(null=True, blank=True, verbose_name='Описание товара')
    price = models.FloatField(verbose_name='Цена')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления записи')
    photo = models.ImageField(upload_to='image/%Y/%m/%d', null=True,blank=True, verbose_name='Фотография товара')
    exists = models.BooleanField(default=True, verbose_name='В наличии?')

    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='Категория')
    tag = models.ManyToManyField(Tag, blank=True, verbose_name='Тег')
    parametr = models.ManyToManyField(Parametr, through='Pos_parametr', verbose_name='Характеристики')

    def get_absolute_url(self):
        return reverse_lazy('product_detail_page', kwargs={'pk': self.pk})
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Pos_parametr(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Продукт')
    parametr = models.ForeignKey(Parametr, on_delete=models.PROTECT, verbose_name='Характеристика')

    value = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Значение')

    def __str__(self):
        return f'{self.product.name} - {self.value}'

    class Meta:
        verbose_name = 'Позиция характеристики'
        verbose_name_plural = 'Позиции характеристик'


class Pos_supply(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Продукт')
    supply = models.ForeignKey(Supply,on_delete=models.PROTECT, verbose_name='Поставка' )

    count = models.PositiveIntegerField(verbose_name='Количество продукта')

    def price_pos_supply(self):
        return sum_price_count(price=self.product.price, count=self.count)
    def __str__(self):
        return f'{self.product.name} - #{self.supply.pk}'

    class Meta:
        verbose_name = 'Позиция поставки'
        verbose_name_plural = 'Позиции поставок'

class Pos_order(models.Model):
    product = models.ForeignKey('Product', on_delete=models.PROTECT, verbose_name='Продукт')
    order = models.ForeignKey('Order', on_delete=models.PROTECT, verbose_name='Заказ')
    count = models.PositiveIntegerField(default=1, verbose_name='Количество продукта')
    discount = models.PositiveIntegerField(default=0, verbose_name='Скидка продукта')

    def sum_pos_order(self):
        return sum_price_count(price=self.product.price, count=self.count, discount=self.discount)

    def __str__(self):
        return f"{self.pk} {self.product.name} {self.order.FIO_customer}"

    class Meta:
        verbose_name = 'Позиция заказа'
        verbose_name_plural = 'Позиции заказов'

magazine/forms.py
import re
from django.core.exceptions import ValidationError
from django import forms
from .models import *

class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = (
            'name',
            'agent_firstname',
            'agent_name',
            'agent_patronymic',
            'agent_telephone',
            'address',
        )

        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'agent_firstname': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'agent_name': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'agent_patronymic': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'agent_telephone': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'address': forms.TextInput(
                attrs={'class': 'form-control'}
            ),

        }
    def clean_agent_telephone(self):
        agent_telephone = self.cleaned_data['agent_telephone']
        if re.match(r'\+7\(\d{3}\)\d{3}-\d{2}-\d{2}', agent_telephone):
            return agent_telephone
        raise ValidationError('Телефон не соответствует шаблону')


class SupplyForm(forms.ModelForm):
    class Meta:
        model = Supply
        fields = (
            'data_supply',
            'supplier',
        )

class Pos_supplyForm(forms.ModelForm):
    class Meta:
        model = Pos_supply
        fields = (
            'product',
            'supply',
            'count',
        )
class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = (
            'name',
            'description',
        )
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = (
            'name',
            'description',
        )
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = (
            'FIO_customer',
            'delivery_address',
            'delivery_type',
            'date_finish'
        )

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            'name',
            'description',
            'price',
            'photo',
            'exists',
            'category',
            'tag',
        )

        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'description': forms.TextInput(
                attrs={'class': 'form-control'}
            ),
            'price': forms.NumberInput(
                attrs={'class': 'form-control'}
            ),
            'photo': forms.FileInput(
                attrs={'class': 'form-control'}
            ),

        }


class ProductFilterForm(forms.Form):
    name = forms.CharField(
        max_length=150,
        min_length=2,
        strip=True,
        label='Название товара',
        required=False,
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )

    )

    max_price = forms.DecimalField(
        label='Максимальная цена товара',
        required=False,
        min_value=0,
        max_digits=10,
        decimal_places=2,
        step_size=0.01,
        widget=forms.NumberInput(
            attrs={'class': 'form-control'}
        )
    )

    min_price = forms.DecimalField(
        label='Минимальная цена товара',
        required=False,
        min_value=0,
        max_digits=10,
        decimal_places=2,
        step_size=0.01,
        widget=forms.NumberInput(
            attrs={'class': 'form-control'}
        )
    )


# ------------------------- auth ---------------------------

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    username = forms.CharField(
        label='Логин пользователя',
        widget=forms.TextInput(attrs={'class': 'form-control', }),
        min_length=2
    )
    email = forms.CharField(
        label='Электронная почта',
        widget=forms.EmailInput(attrs={'class': 'form-control', }),
    )
    password1 = forms.CharField(
        label='Придумайте пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control', }),
    )
    password2 = forms.CharField(
        label='Повторите пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control', }),
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Логин пользователя',
        widget=forms.TextInput(attrs={'class': 'form-control', }),
        min_length=2
    )
    password = forms.CharField(
        label='Ваш пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control', }),
    )

magazine/templates/magazine/order/order_confirm_delete.html
{% extends 'base.html' %}

{% block title_name %}
    Удаление: {{ object.pk }}
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h1>Вы действительно хотите удалить заказ: {{ object.pk }}</h1>
        <div>
            {{ object.FIO_customer }}
        </div>
        <button class="btn btn-danger" type="submit">Да</button>
    </form>
{% endblock %}

{% block additional_content %}
    <a class="btn btn-outline-success" href="{% url 'order_view_list' %}">Нет</a>
{% endblock %}

magazine/templates/magazine/order/order_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title_name %}
    Удаление объекта
{% endblock %}

{% block content %}
    <h1>Подвтердить удаление?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Да</button>
    </form>
        <a href="{% url 'order_list' %}" class="btn btn-success">Нет</a>
{% endblock %}

magazine/templates/magazine/order/order_detail.html
{% extends 'base.html' %}
{% block title_name %}
    Заказ: {{ object.pk }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                {{ order.FIO_customer }}
            </div>
            <div class="col">
                {{ order.delivery_address }}
                {{ order.get_delivery_type_display }}
            </div>
        </div>
        <div class="row row-cols-1">
            {% for pos_product in object.pos_order_set.all %}
                <div class="col">
                    <a href="{% url 'product_detail_page' pos_product.product.pk %}">
                        {{ pos_product.product.name }}
                    </a>: {{ pos_product.product.price }} * {{ pos_product.count }} | {{ pos_product.discount }} %
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block additional_content %}
    <a class="btn btn-success" href="{% url 'order_list' %}">Вернуться к списку заказов</a>

    {% if perms.magazine.change_order %}
         <a href="{% url 'order_update' object.pk%}" class="btn btn-warning">Изменить</a>
    {% endif %}

    {% if perms.magazine.delete_order %}
        <form method="post" action="{% url 'order_delete' object.pk %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
    {% endif %}

{% endblock %}

magazine/templates/magazine/order/order_form.html
{% extends 'base.html' %}

{% block title_name %}
    {{ action }} заказа {{ object.pk }}
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-danger" type="submit">{{ action_button }} заказа</button>
    </form>
{% endblock %}

{% block additional_content %}
    <a class="btn btn-warning" href="{% url 'order_list' %}">Вернуться к списки заказов</a>
{% endblock %}

magazine/templates/magazine/order/order_list.html
{% extends 'base.html' %}

{% block title_name %}
    Список заказов
{% endblock %}

{% block content %}
    <div class="container">
        {% for object in object_list %}
            <div class="row">
                <div class="col col-3">
                    <a href="{{ object.get_absolute_url }}">{{ object.FIO_customer }}</a>
                </div>
                <div class="col col-3">
                    {{ object.delivery_address }} - {{ object.get_delivery_type_display }}
                </div>
                <div class="col col-6">
                    Товары:
                    {% for product in object.books.all %}
                        {{ product.name }}
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block additional_content %}
    {% if perms.magazine.add_order %}
        <a class="btn btn-primary" href="{% url 'order_create' %}">Создать заказ</a>
    {% endif %}
{% endblock %}